twig:
    default_path: '%app.paths.templates%twig'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    paths:
        'lib/twig': ~
when@test:
    twig:
        strict_variables: true
