parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # bind processwire to the constructor variable $processWire to get injected if a service needs it
            $processWire: '@processwire'
    App\:
        resource: '%kernel.project_dir%/src/'
